server:
  port: 8761

spring:
  application:
    name: EUREKA-SERVER

eureka:
  instance:
    hostname: localhost
  client:
    # Do not register the Eureka server itself as a client
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
  server:
    # Reduce wait time in development
    wait-time-in-ms-when-sync-empty: 0

logging:
  level:
    com.netflix.eureka: WARN
    com.netflix.discovery: WARN
